### ISSUE TITLE
Export NetworkError

### ISSUE THREAD

**Issue by CyanoFresh** [s3pweb/keycloak-admin-client-cjs#21]
Hi!
Thanks for your package!
Could you please include `NetworkError` from https://github.com/keycloak/keycloak/blob/main/js/libs/keycloak-admin-client/src/utils/fetchWithError.ts in the built files?
I couldn't find the place where I can fix it and open PR

**Comment by Mualig** [comment]
I'm adding it.
Exported models are here: dist/index.d.ts

**Comment by Mualig** [comment]
Version 25.1.0 is released with NetworkError exported
